"use client";

import {AlertTriangle, Archive, CalendarDays, Check, ChevronRight, CircleDollarSign, Clock3, Download, Edit3, Eye, FileSpreadsheet, FileUp, Filter, History, MapPin, Plus, Puzzle, RefreshCw, Save, ShieldCheck, Trash2, UserRound, Users, WandSparkles, X} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase/client";
import * as XLSX from "xlsx";

export type AdminEmployee={id:string;employeeNo:string;firstName:string;lastName:string;email:string;primaryRole:string;nominalMinutes:number;maxWeeklyMinutes:number;maxMonthlyMinutes:number;preferredShift?:string;active:boolean;archivedAt?:string;archiveReason?:string;locations:{code:string;name:string;home:boolean;standard:boolean;overtime:boolean}[];capabilities:{id:string;capability:string;role?:string;location?:string}[];hr?:{contract_type:string;employment_fraction:number;leave_days:number;hr_note?:string};finance?:{hourlyRate:number}};
export type MatrixItem={id:string;code:string;name:string;color?:string;description?:string;active:boolean;starts_at?:string;ends_at?:string;location_id?:string;day_mask?:number[]};
export type Section={id:string;roleId:string;roleCode:string;roleName:string;version:number;status:string;name:string;createdAt:string;updatedAt:string;planId?:string;assignmentCount:number;issueCount:number};
export type CompleteWorkspace={counts:{employees:number;archivedEmployees:number;roleManagers:number;locations:number};employees:AdminEmployee[];activeMatrix?:{id:string;version:number;name:string;status:string};draftMatrix?:{id:string;version:number;name:string;status:string};roles:MatrixItem[];functions:MatrixItem[];locations:MatrixItem[];shifts:MatrixItem[];demand:{id:string;shift_template_id:string;role_id:string;function_id?:string;required_count:number;scenario_code:string}[];sections:Section[];budget:{amount?:number;warning_percent?:number;hard_limit?:boolean};preferences:unknown[];integrationRuns:{id:string;integration:string;direction:string;status:string;file_name?:string;created_at:string}[];timeRecords:{id:string;employee_id:string;work_date:string;planned_start?:string;planned_end?:string;actual_start?:string;actual_end?:string;status:string}[]};
type PortalAssignment={id:string;shiftId?:string;date:string;startsAt:string;endsAt:string;shiftCode?:string;location:string;locationCode?:string;role:string;capability?:string;coworkers?:{name:string;role:string;capability?:string}[]};
type PortalWorkspace={employee?:{id:string;employeeNo:string;firstName:string;lastName:string;primaryRole:string;locations:{code:string;name:string}[]};preferences:any[];availability:{date:string;status:"AVAILABLE"|"UNAVAILABLE";source:string;note?:string}[];availabilityHistory:any[];assignments:PortalAssignment[];attendance:{id:string;action:string;occurredAt:string;location:string}[]};
type View="kadra"|"matrixAdmin"|"rolePlans"|"hr"|"finanse"|"portal"|"czas"|"integracje";
const rolePl:Record<string,string>={KELNER:"Kelner",BARMAN:"Barman",PIZZABAR:"Pizzabar",PREP:"Prep",POMOC:"Pomoc"};
const statusPl:Record<string,string>={DRAFT:"Nie utworzono",GENERATING:"Generowanie",READY:"Wersja robocza",SUBMITTED:"Przekazany do zatwierdzenia",CHANGES_REQUESTED:"Do poprawy",APPROVED:"Zatwierdzony",LOCKED:"Zablokowany",ARCHIVED:"Archiwalny"};
const days=["Pon","Wt","Śr","Czw","Pt","Sob","Niedz"];

export function CompleteModules({view,data,reload,notify,fail}:{view:View;data:CompleteWorkspace;reload:()=>Promise<void>;notify:(s:string)=>void;fail:(s:string)=>void}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const [busy,setBusy]=useState(false);const [tab,setTab]=useState("aktywni");const [search,setSearch]=useState("");const [editEmployee,setEditEmployee]=useState<AdminEmployee|null>(null);const [preferenceEmployee,setPreferenceEmployee]=useState<AdminEmployee|null>(null);const [availabilityEmployee,setAvailabilityEmployee]=useState<AdminEmployee|null>(null);const [matrixEdit,setMatrixEdit]=useState<{kind:string;item?:MatrixItem}|null>(null);const [roleDetail,setRoleDetail]=useState<{section:Section;assignments:any[];issues:any[]}|null>(null);const [portal,setPortal]=useState<PortalWorkspace|null>(null);const [clockLocation,setClockLocation]=useState("");const [budget,setBudget]=useState({amount:String(data.budget?.amount||0),warning:String(data.budget?.warning_percent||90),hard:Boolean(data.budget?.hard_limit)});
 useEffect(()=>{if(!supabase||!(view==="portal"||view==="czas"))return;void supabase.rpc("employee_portal_workspace",{p_month:"2026-07-01"}).then(r=>{if(!r.error&&r.data){setPortal(r.data as PortalWorkspace);setClockLocation((r.data as PortalWorkspace).employee?.locations?.[0]?.code||"")}})},[supabase,view]);
 async function rpc(name:string,args:Record<string,unknown>){if(!supabase)return undefined;setBusy(true);const r=await supabase.rpc(name,args);setBusy(false);if(r.error){fail(translateError(r.error.message));return undefined}return r.data??true}
 async function archive(e:AdminEmployee){const reason=window.prompt(`Powód archiwizacji pracownika ${e.firstName} ${e.lastName}:`,"");if(reason===null)return;const ok=await rpc("employee_archive",{p_employee_id:e.id,p_reason:reason});if(ok){notify("Pracownik został przeniesiony do archiwum");await reload()}}
 async function restore(e:AdminEmployee){const ok=await rpc("employee_restore",{p_employee_id:e.id});if(ok){notify("Pracownik został przywrócony");await reload()}}
 async function saveEmployee(form:HTMLFormElement){if(!editEmployee)return;const f=new FormData(form);const payload=Object.fromEntries(f.entries());const ok=await rpc("employee_update",{p_employee_id:editEmployee.id,p_data:payload});if(ok){setEditEmployee(null);notify("Dane pracownika zapisano w Supabase");await reload()}}
 async function createDraft(){const name=window.prompt("Nazwa nowej wersji Matrixa:",`Matrix v${(data.activeMatrix?.version||0)+1}`);if(!name)return;const ok=await rpc("matrix_create_draft",{p_name:name});if(ok){notify("Utworzono wersję roboczą Matrixa");await reload()}}
 async function saveMatrix(form:HTMLFormElement){if(!matrixEdit)return;const payload=Object.fromEntries(new FormData(form).entries());const ok=await rpc("matrix_save_item",{p_kind:matrixEdit.kind,p_id:matrixEdit.item?.id||null,p_data:payload});if(ok){setMatrixEdit(null);notify("Zmiana zapisana w wersji roboczej Matrixa");await reload()}}
 async function publishMatrix(){if(!confirm("Opublikować wersję roboczą Matrixa? Historia poprzedniej wersji zostanie zachowana."))return;const ok=await rpc("matrix_publish_draft",{p_effective_from:new Date().toISOString().slice(0,10)});if(ok){notify("Nowa wersja Matrixa została aktywowana");await reload()}}
 async function saveShift(form:HTMLFormElement){if(!matrixEdit)return;const payload=Object.fromEntries(new FormData(form).entries());const ok=await rpc("matrix_save_shift",{p_id:matrixEdit.item?.id||null,p_data:payload});if(ok){setMatrixEdit(null);notify("Definicja zmiany została zapisana");await reload()}}
 async function saveDemand(shiftId:string,roleId:string,value:number){const ok=await rpc("matrix_save_demand",{p_shift_id:shiftId,p_role_id:roleId,p_required:value,p_scenario:"BASE"});if(ok){notify("Zapotrzebowanie zapisano");await reload()}}
 async function importMatrix(file:File){try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});const required=["LOKALE","ROLE","FUNKCJE","ZMIANY","OBSADA_BAZOWA","SCENARIUSZE","PRACOWNICY"];const missing=required.filter(n=>!wb.Sheets[n]);if(missing.length){fail(`Brakuje arkuszy: ${missing.join(", ")}`);return}const rows=(name:string)=>XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:""});const payload={locations:rows("LOKALE"),roles:rows("ROLE"),functions:rows("FUNKCJE"),shifts:rows("ZMIANY"),demand:rows("OBSADA_BAZOWA"),scenarios:rows("SCENARIUSZE"),employees:rows("PRACOWNICY")};const permissionRequests=(payload.employees as any[]).filter(x=>String(x.SUGEROWANY_DOSTEP||"").trim()).map(x=>({employeeNo:x.NUMER_PRACOWNIKA,requestedAccess:x.SUGEROWANY_DOSTEP}));if(!confirm(`Plik przeszedł kontrolę struktury. Import utworzy wersję roboczą Matrixa. ${permissionRequests.length?`Zawiera ${permissionRequests.length} sugestii dostępu — NIE zostaną automatycznie zastosowane.`:"Nie zawiera zmian dostępów."} Kontynuować?`))return;const ok=await rpc("matrix_import_apply",{p_file_name:file.name,p_payload:payload,p_requested_permissions:permissionRequests});if(ok){notify(`Zaimportowano wersję roboczą: ${ok.roles} ról, ${ok.shifts} zmian i ${ok.demand} reguł obsady. Dostępy pozostały bez zmian.`);await reload()}}catch(e){fail(`Nie udało się odczytać pliku Excel: ${e instanceof Error?e.message:String(e)}`)}}
 async function generateRole(role:MatrixItem){const result=await rpc("generate_role_plan",{p_month:"2026-07-01",p_role_id:role.id,p_name:`Grafik ${role.name} • lipiec 2026`,p_scenario:"BASE",p_mode:"BALANCED",p_staffing:"OPTIMAL"});if(result){notify(`Wygenerowano ${result.assignments} rzeczywistych przydziałów dla roli ${role.name}`);await reload()}}
 async function openSection(s:Section){const result=await rpc("role_plan_workspace",{p_section_id:s.id});if(result)setRoleDetail({section:s,assignments:result.assignments||[],issues:result.issues||[]})}
 async function transition(s:Section,status:string){const ok=await rpc("transition_role_plan",{p_section_id:s.id,p_status:status});if(ok){notify(`Status: ${statusPl[status]}`);await reload()}}
 async function assemble(){const name=window.prompt("Nazwa nowej wersji grafiku operacyjnego:","Grafik operacyjny • lipiec 2026");if(!name)return;const result=await rpc("assemble_role_plans",{p_month:"2026-07-01",p_name:name});if(result){notify(`Scalono ${result.sections} grafików ról i ${result.assignments} przydziałów. Powstała wersja robocza v${result.version}.`);await reload()}}
 async function saveBudget(){const ok=await rpc("budget_update",{p_month:"2026-07-01",p_amount:Number(budget.amount),p_warning_percent:Number(budget.warning),p_hard_limit:budget.hard});if(!ok)return;notify("Budżet zapisano w chronionej sekcji");await reload()}
 async function savePreference(form:HTMLFormElement){if(!preferenceEmployee)return;const f=new FormData(form);const ok=await rpc("preference_save",{p_employee_id:preferenceEmployee.id,p_from:f.get("from"),p_to:f.get("to"),p_type:f.get("type"),p_value:{value:f.get("value"),note:f.get("note")}});if(ok){setPreferenceEmployee(null);notify("Preferencja pracownika została zapisana");await reload()}}
 async function saveAvailability(entries:{date:string;status:string}[],defaultRemaining:boolean){const ok=await rpc("employee_availability_save_month",{p_month:"2026-07-01",p_entries:entries,p_default_remaining_available:defaultRemaining});if(ok){setAvailabilityEmployee(null);notify(`Dostępność zapisana. ${ok.saved||0} dni zmieniono, ${ok.defaultedAvailable||0} dni oznaczono jako dostępne.`);await reload()}}
 async function saveRoleAssignment(section:Section,assignmentId:string|null,payload:Record<string,unknown>){const ok=await rpc("role_plan_assignment_save",{p_section_id:section.id,p_assignment_id:assignmentId,p_data:payload});if(ok){notify("Przydział zapisano w wersji roboczej");await openSection(section);await reload()}}
 async function deleteRoleAssignment(section:Section,assignmentId:string){if(!confirm("Usunąć ten przydział z wersji roboczej?"))return;const ok=await rpc("role_plan_assignment_delete",{p_section_id:section.id,p_assignment_id:assignmentId});if(ok){notify("Przydział usunięto");await openSection(section);await reload()}}
 async function exportKadromierz(){const rows=await rpc("kadromierz_export",{p_month:"2026-07-01"});if(Array.isArray(rows))downloadCsv("grafik-kadromierz-2026-07.csv",rows)}
 async function importKadromierz(file:File){const text=await file.text();const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2){fail("Plik CSV nie zawiera danych.");return}const separator=lines[0].includes(";")?";":",";const headers=lines[0].split(separator).map(x=>x.trim().toLowerCase());const rows=lines.slice(1).map(line=>Object.fromEntries(line.split(separator).map((v,i)=>[headers[i],v.trim()])));const result=await rpc("kadromierz_import_preferences",{p_file_name:file.name,p_rows:rows});if(result){notify(`Zaimportowano ${result.imported} pozycji; pominięto ${result.skipped}`);await reload()}}
 async function clock(action:"CHECK_IN"|"CHECK_OUT"){if(!clockLocation){fail("Wybierz lokal.");return}if(!navigator.geolocation){fail("Przeglądarka nie obsługuje geolokalizacji.");return}navigator.geolocation.getCurrentPosition(async pos=>{const ok=await rpc("attendance_clock",{p_action:action,p_location:clockLocation,p_latitude:pos.coords.latitude,p_longitude:pos.coords.longitude});if(ok){notify(action==="CHECK_IN"?"Rozpoczęcie pracy zapisano":"Zakończenie pracy zapisano");const r=await supabase?.rpc("employee_portal_workspace",{p_month:"2026-07-01"});if(r&&!r.error)setPortal(r.data as PortalWorkspace)}},()=>fail("Nie udało się pobrać lokalizacji. Zezwól przeglądarce na dostęp do lokalizacji."),{enableHighAccuracy:true,timeout:12000})}

 if(view==="kadra")return <><PageHead eyebrow="KADRA • DANE Z SUPABASE" title="Pracownicy" subtitle={`${data.counts.employees} aktywnych • ${data.counts.archivedEmployees} w archiwum • ${data.counts.roleManagers} menadżerów`}/><div className="module-tabs"><button className={tab==="aktywni"?"active":""} onClick={()=>setTab("aktywni")}>Aktywni ({data.counts.employees})</button><button className={tab==="archiwum"?"active":""} onClick={()=>setTab("archiwum")}>Archiwum ({data.counts.archivedEmployees})</button></div><div className="admin-toolbar"><label><Users/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Szukaj po nazwisku, numerze lub roli"/></label></div><EmployeeTable rows={data.employees.filter(e=>(tab==="aktywni"?e.active:!e.active)&&`${e.firstName} ${e.lastName} ${e.employeeNo} ${e.primaryRole}`.toLowerCase().includes(search.toLowerCase()))} edit={setEditEmployee} archive={archive} restore={restore}/>{editEmployee&&<EmployeeDrawer employee={editEmployee} close={()=>setEditEmployee(null)} save={saveEmployee} busy={busy}/>}</>;
 if(view==="matrixAdmin")return <><PageHead eyebrow="WERSJONOWANA KONFIGURACJA" title="Matrix organizacji" subtitle="Edycja odbywa się w wersji roboczej. Opublikowane grafiki zachowują swoją wersję konfiguracji." actions={<>{!data.draftMatrix?<button className="primary-button" onClick={createDraft}><Plus/> Nowa wersja robocza</button>:<button className="primary-button" onClick={publishMatrix}><Check/> Opublikuj Matrix v{data.draftMatrix.version}</button>}</>}/><div className="matrix-version-strip"><History/><span><b>Aktywna: {data.activeMatrix?.name} • v{data.activeMatrix?.version}</b><small>{data.draftMatrix?`Edytujesz wersję roboczą v${data.draftMatrix.version}`:"Brak niezapisanych zmian"}</small></span></div><MatrixColumns data={data} editable={Boolean(data.draftMatrix)} edit={(kind,item)=>setMatrixEdit({kind,item})} saveDemand={saveDemand} importMatrix={importMatrix}/>{matrixEdit&&<MatrixDrawer edit={matrixEdit} data={data} close={()=>setMatrixEdit(null)} save={matrixEdit.kind==="SHIFT"?saveShift:saveMatrix} busy={busy}/>}</>;
 if(view==="rolePlans")return <><PageHead eyebrow="PLANOWANIE ZESPOŁOWE" title="Grafiki według roli" subtitle="Każdy grafik pozostaje wersją roboczą, dopóki lider świadomie go nie przekaże. Puste lub nieudane wersje można wygenerować ponownie." actions={<button className="primary-button" disabled={!data.sections.some(s=>s.status==="APPROVED")} onClick={assemble}><Puzzle/> Scal zatwierdzone grafiki</button>}/><div className="role-plan-cards">{data.roles.filter(r=>r.active).map(r=>{const sections=data.sections.filter(s=>s.roleCode===r.code);const s=sections.sort((a,b)=>b.version-a.version)[0];const empty=!s||s.assignmentCount===0;return <article key={r.id}><i style={{background:r.color||"#7257d8"}}/><div><small>GRAFIK ROLI</small><h3>{r.name}</h3><p>{s?`${s.name} • wersja ${s.version}`:"Nie utworzono grafiku"}</p></div><span className={`workflow-status ${empty?"empty":s?.status?.toLowerCase()}`}>{empty?(s?"Generowanie nieudane":"Nie utworzono"):statusPl[s!.status]}</span><strong>{s?.assignmentCount||0}</strong><small>rzeczywistych przydziałów tej roli</small><div className="card-actions">{empty&&<button disabled={busy} className="primary-button" onClick={()=>generateRole(r)}><WandSparkles/> {s?"Generuj ponownie":"Generuj grafik"}</button>}{s&&s.assignmentCount>0&&<button className="secondary-button" onClick={()=>openSection(s)}>Kalendarz i edycja <ChevronRight/></button>}{s?.assignmentCount>0&&s.status==="READY"&&<button className="primary-button" onClick={()=>transition(s,"SUBMITTED")}>Przekaż</button>}{s?.assignmentCount>0&&s.status==="SUBMITTED"&&<button className="primary-button" onClick={()=>transition(s,"APPROVED")}>Zatwierdź</button>}</div></article>})}</div>{roleDetail&&<RoleDrawer detail={roleDetail} employees={data.employees} locations={data.locations} close={()=>setRoleDetail(null)} save={saveRoleAssignment} remove={deleteRoleAssignment}/>}</>;
 if(view==="hr")return <><PageHead eyebrow="CHRONIONY MODUŁ" title="Kadry i HR" subtitle="Dane zatrudnienia, wymiar czasu, urlopy i notatki HR. Dostęp: właściciel, administrator i HR/finanse."/><div className="protected-banner"><ShieldCheck/><span><b>Sekcja chroniona uprawnieniami</b><small>Dane nie są pokazywane liderom zespołów ani innym pracownikom.</small></span></div><div className="hr-grid">{data.employees.filter(e=>e.active).map(e=><button key={e.id} onClick={()=>setEditEmployee(e)}><span><b>{e.firstName} {e.lastName}</b><small>{e.employeeNo} • {rolePl[e.primaryRole]}</small></span><span><b>{contractPl(e.hr?.contract_type)}</b><small>{Math.round(e.nominalMinutes/60)} godz./mies. • urlop: {e.hr?.leave_days||0} dni</small></span><Edit3/></button>)}</div>{editEmployee&&<EmployeeDrawer employee={editEmployee} close={()=>setEditEmployee(null)} save={saveEmployee} busy={busy}/>}</>;
 if(view==="finanse")return <><PageHead eyebrow="CHRONIONY MODUŁ" title="Finanse i budżet" subtitle="Stawki są oddzielone od zwykłego planowania, ale wpływają na koszt wariantu i kontrolę nadgodzin."/><div className="finance-layout"><section className="finance-budget"><CircleDollarSign/><span><small>BUDŻET • LIPIEC 2026</small><input type="number" value={budget.amount} onChange={e=>setBudget({...budget,amount:e.target.value})}/><em>zł</em></span><label>Ostrzeżenie przy <input type="number" min="1" max="100" value={budget.warning} onChange={e=>setBudget({...budget,warning:e.target.value})}/>%</label><label className="checkbox"><input type="checkbox" checked={budget.hard} onChange={e=>setBudget({...budget,hard:e.target.checked})}/> Twardy limit budżetu</label><button className="primary-button" onClick={saveBudget}><Save/> Zapisz budżet</button></section><section className="rate-list"><h3>Chronione stawki pracowników</h3>{data.employees.filter(e=>e.active).map(e=><button key={e.id} onClick={()=>setEditEmployee(e)}><span>{e.firstName} {e.lastName}<small>{rolePl[e.primaryRole]}</small></span><b>{e.finance?.hourlyRate??"—"} zł/h</b><Edit3/></button>)}</section></div>{editEmployee&&<EmployeeDrawer employee={editEmployee} close={()=>setEditEmployee(null)} save={saveEmployee} busy={busy}/>}</>;
 if(view==="portal")return <>{portal?<EmployeePortal portal={portal} openAvailability={()=>{const e=data.employees.find(x=>x.id===portal.employee?.id);if(e)setAvailabilityEmployee(e)}} openPreferences={()=>{const e=data.employees.find(x=>x.id===portal.employee?.id);if(e)setPreferenceEmployee(e)}}/>:<div className="empty-state">Konto nie jest powiązane z pracownikiem.</div>}{availabilityEmployee&&<AvailabilityDrawer employee={availabilityEmployee} existing={portal?.availability||[]} close={()=>setAvailabilityEmployee(null)} save={saveAvailability} busy={busy}/>} {preferenceEmployee&&<PreferenceDrawer employee={preferenceEmployee} locations={portal?.employee?.locations||[]} close={()=>setPreferenceEmployee(null)} save={savePreference} busy={busy}/>}</>;
 if(view==="czas")return <TimeView employees={data.employees} records={data.timeRecords} portal={portal} location={clockLocation} setLocation={setClockLocation} clock={clock} busy={busy}/>;
 return <IntegrationView runs={data.integrationRuns} onExport={exportKadromierz} onImport={importKadromierz} busy={busy}/>;
}

function PageHead({eyebrow,title,subtitle,actions}:{eyebrow:string;title:string;subtitle:string;actions?:React.ReactNode}){return <div className="module-page-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{subtitle}</p></div><div>{actions}</div></div>}
function EmployeeTable({rows,edit,archive,restore}:{rows:AdminEmployee[];edit:(e:AdminEmployee)=>void;archive:(e:AdminEmployee)=>void;restore:(e:AdminEmployee)=>void}){return <div className="admin-table"><div className="admin-tr head"><span>Pracownik</span><span>Rola</span><span>Lokal bazowy</span><span>Nominał</span><span>Funkcje</span><span>Operacje</span></div>{rows.map(e=><div className="admin-tr" key={e.id}><span><b>{e.firstName} {e.lastName}</b><small>{e.employeeNo}</small></span><span>{rolePl[e.primaryRole]}</span><span><MapPin/>{e.locations.find(l=>l.home)?.name||"—"}</span><span>{Math.round(e.nominalMinutes/60)} godz.</span><span>{e.capabilities.map(c=>capPl(c.capability)).join(", ")||"—"}</span><span><button title="Edytuj" onClick={()=>edit(e)}><Edit3/></button>{e.active?<button title="Archiwizuj" onClick={()=>archive(e)}><Archive/></button>:<button title="Przywróć" onClick={()=>restore(e)}><RefreshCw/></button>}</span></div>)}</div>}
function EmployeeDrawer({employee,close,save,busy}:{employee:AdminEmployee;close:()=>void;save:(f:HTMLFormElement)=>void;busy:boolean}){return <><button className="drawer-scrim" onClick={close}/><aside className="drawer complete-drawer"><div className="drawer-head"><div><p className="eyebrow">PRACOWNIK • {employee.employeeNo}</p><h2>{employee.firstName} {employee.lastName}</h2></div><button className="icon-button" onClick={close}><X/></button></div><form className="drawer-content" onSubmit={e=>{e.preventDefault();save(e.currentTarget)}}><div className="form-row"><label>Imię<input name="firstName" defaultValue={employee.firstName}/></label><label>Nazwisko<input name="lastName" defaultValue={employee.lastName}/></label></div><label>E-mail<input name="email" type="email" defaultValue={employee.email}/></label><label>Rola podstawowa<select name="primaryRole" defaultValue={employee.primaryRole}>{Object.entries(rolePl).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><div className="form-row"><label>Nominał miesięczny (min)<input name="nominalMinutes" type="number" defaultValue={employee.nominalMinutes}/></label><label>Limit tygodniowy (min)<input name="maxWeeklyMinutes" type="number" defaultValue={employee.maxWeeklyMinutes}/></label></div><label>Preferowana zmiana<select name="preferredShift" defaultValue={employee.preferredShift||""}><option value="">Bez preferencji</option><option value="RANO">Poranna</option><option value="SRODEK">Środkowa</option><option value="WIECZOR">Wieczorna</option></select></label><h3>Kadry i HR</h3><div className="form-row"><label>Rodzaj umowy<select name="contractType" defaultValue={employee.hr?.contract_type||"UMOWA_O_PRACE"}><option value="UMOWA_O_PRACE">Umowa o pracę</option><option value="ZLECENIE">Zlecenie</option><option value="CZESC_ETATU">Część etatu</option><option value="B2B">B2B</option><option value="INNE">Inna</option></select></label><label>Wymiar etatu<input name="employmentFraction" type="number" step="0.1" min="0.1" max="1" defaultValue={employee.hr?.employment_fraction||1}/></label></div><label>Dni urlopu<input name="leaveDays" type="number" min="0" defaultValue={employee.hr?.leave_days||0}/></label><label>Notatka HR<textarea name="hrNote" defaultValue={employee.hr?.hr_note||""}/></label><h3>Finanse — dane chronione</h3><label>Stawka godzinowa<input name="hourlyRate" type="number" step="0.01" defaultValue={employee.finance?.hourlyRate||""}/></label><button disabled={busy} className="primary-button full"><Save/> Zapisz w Supabase</button></form></aside></>}
function MatrixColumns({data,editable,edit,saveDemand,importMatrix}:{data:CompleteWorkspace;editable:boolean;edit:(k:string,i?:MatrixItem)=>void;saveDemand:(s:string,r:string,n:number)=>void;importMatrix:(f:File)=>void}){
 const [location,setLocation]=useState("ALL");const [weekday,setWeekday]=useState("ALL");const [scenario,setScenario]=useState("BASE");
 const activeRoles=data.roles.filter(r=>r.active);const filtered=data.shifts.filter(s=>(location==="ALL"||s.location_id===location)&&(weekday==="ALL"||s.day_mask?.includes(Number(weekday))));
 function exportExcel(){const wb=XLSX.utils.book_new();const add=(name:string,rows:any[])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),name);
  add("INSTRUKCJA",[{INFORMACJA:"Edytuj tabele, zachowując kody. Import tworzy wersję roboczą i nigdy automatycznie nie zmienia dostępów."}]);
  add("LOKALE",data.locations.map(x=>({KOD:x.code,NAZWA:x.name,AKTYWNY:x.active?"TAK":"NIE"})));
  add("ROLE",data.roles.map(x=>({KOD:x.code,NAZWA:x.name,KOLOR:x.color||"#7457e8",AKTYWNA:x.active?"TAK":"NIE"})));
  add("FUNKCJE",data.functions.map(x=>({KOD:x.code,NAZWA:x.name,OPIS:x.description||"",AKTYWNA:x.active?"TAK":"NIE"})));
  add("ZMIANY",data.shifts.map(s=>{const l=data.locations.find(x=>x.id===s.location_id);return {KOD:s.code,NAZWA:s.name,LOKAL:l?.code,OD:s.starts_at?.slice(0,5),DO:s.ends_at?.slice(0,5),DNI:(s.day_mask||[]).join(","),AKTYWNA:s.active?"TAK":"NIE"}}));
  add("OBSADA_BAZOWA",data.demand.map(d=>{const s=data.shifts.find(x=>x.id===d.shift_template_id),r=data.roles.find(x=>x.id===d.role_id),l=data.locations.find(x=>x.id===s?.location_id);return {SCENARIUSZ:d.scenario_code,LOKAL:l?.code,ZMIANA:s?.code,ROLA:r?.code,WYMAGANE:d.required_count}}));
  add("SCENARIUSZE",["BASE","LOW","HIGH","WEEKEND","EVENT","SUMMER","EMERGENCY"].map((code,i)=>({KOD:code,NAZWA:["Bazowy","Niski ruch","Wysoki ruch","Weekend","Event","Sezon letni","Awaryjny"][i],AKTYWNY:"TAK"})));
  add("PRACOWNICY",data.employees.map(e=>({NUMER_PRACOWNIKA:e.employeeNo,IMIE:e.firstName,NAZWISKO:e.lastName,ROLA:e.primaryRole,LOKALE:e.locations.map(l=>l.code).join(","),FUNKCJE:e.capabilities.map(c=>c.capability).join(","),SUGEROWANY_DOSTEP:""})));
  XLSX.writeFile(wb,"GRAFIK_PRO_MATRIX_2026_07.xlsx");}
 const groups=data.locations.filter(l=>location==="ALL"||l.id===location);
 return <><div className="matrix-import-toolbar"><button className="secondary-button" onClick={exportExcel}><FileSpreadsheet/> Pobierz Matrix Excel</button><label className="primary-button"><FileUp/> Importuj Matrix Excel<input hidden type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&importMatrix(e.target.files[0])}/></label><small>Import tworzy wersję roboczą. Sugestie dostępów wymagają osobnego zatwierdzenia właściciela.</small></div>
 <div className="matrix-admin-grid">{[{title:"Role podstawowe",kind:"ROLE",items:data.roles},{title:"Funkcje i obowiązki",kind:"FUNCTION",items:data.functions},{title:"Lokale",kind:"LOCATION",items:data.locations}].map(c=><details key={c.kind}><summary><h3>{c.title}</h3><span>{c.items.length}</span></summary><div className="matrix-details-actions">{editable&&<button onClick={()=>edit(c.kind)}><Plus/> Dodaj</button>}</div>{c.items.map(i=><button className="matrix-admin-row" key={i.id} onClick={()=>editable&&edit(c.kind,i)}><i style={{background:i.color||"#8a8493"}}/><span><b>{i.name}</b><small>{i.description||i.code}</small></span><em>{i.active?"Aktywna":"Archiwalna"}</em>{editable&&<Edit3/>}</button>)}</details>)}</div>
 <section className="matrix-demand"><div className="matrix-demand-head"><div><h3>Zmiany i wymagana obsada</h3><p>Filtruj lokal, dzień i scenariusz. Lokale są pogrupowane, a sekcje można zwijać.</p></div>{editable&&<button className="secondary-button" onClick={()=>edit("SHIFT")}><Plus/> Dodaj zmianę</button>}</div>
 <div className="matrix-filters"><Filter/><button className={location==="ALL"?"active":""} onClick={()=>setLocation("ALL")}>Wszystkie lokale</button>{data.locations.filter(l=>l.active).map(l=><button className={location===l.id?"active":""} onClick={()=>setLocation(l.id)} key={l.id}>{l.name}</button>)}<select value={weekday} onChange={e=>setWeekday(e.target.value)}><option value="ALL">Wszystkie dni</option>{days.map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select><select value={scenario} onChange={e=>setScenario(e.target.value)}>{["BASE","LOW","HIGH","WEEKEND","EVENT","SUMMER","EMERGENCY"].map(x=><option value={x} key={x}>{scenarioPl(x)}</option>)}</select></div>
 {groups.map(loc=><details className="matrix-location-group" open key={loc.id}><summary><MapPin/><b>{loc.name}</b><span>{filtered.filter(s=>s.location_id===loc.id).length} zmian</span></summary><div className="demand-table"><div className="demand-row head"><span>Zmiana</span>{activeRoles.map(r=><span key={r.id}>{r.name}</span>)}<span>Operacje</span></div>{filtered.filter(s=>s.location_id===loc.id).map(s=><div className="demand-row" key={s.id}><span><b>{s.name}</b><small>{s.starts_at?.slice(0,5)}–{s.ends_at?.slice(0,5)} • {s.day_mask?.map(d=>days[d-1]).join(", ")}</small></span>{activeRoles.map(r=>{const d=data.demand.find(x=>x.shift_template_id===s.id&&x.role_id===r.id&&!x.function_id&&x.scenario_code===scenario);return <label key={r.id}><input disabled={!editable} type="number" min="0" value={d?.required_count||0} onChange={e=>editable&&saveDemand(s.id,r.id,Number(e.target.value))}/></label>})}<span>{editable&&<button title="Edytuj zmianę" onClick={()=>edit("SHIFT",s)}><Edit3/></button>}</span></div>)}</div></details>)}</section></>}
function MatrixDrawer({edit,data,close,save,busy}:{edit:{kind:string;item?:MatrixItem};data:CompleteWorkspace;close:()=>void;save:(f:HTMLFormElement)=>void;busy:boolean}){const shift=edit.kind==="SHIFT";return <><button className="drawer-scrim" onClick={close}/><aside className="drawer complete-drawer"><div className="drawer-head"><div><p className="eyebrow">WERSJA ROBOCZA MATRIXA</p><h2>{edit.item?"Edytuj":"Dodaj"} {shift?"zmianę":edit.kind==="ROLE"?"rolę":edit.kind==="FUNCTION"?"funkcję":"lokal"}</h2></div><button className="icon-button" onClick={close}><X/></button></div><form className="drawer-content" onSubmit={e=>{e.preventDefault();save(e.currentTarget)}}>{shift&&<label>Lokal<select name="locationId" required defaultValue={edit.item?.location_id}>{data.locations.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<label>Kod<input name="code" required defaultValue={edit.item?.code}/></label><label>Nazwa<input name="name" required defaultValue={edit.item?.name}/></label>{shift&&<><div className="form-row"><label>Od<input name="startsAt" type="time" required defaultValue={edit.item?.starts_at?.slice(0,5)}/></label><label>Do<input name="endsAt" type="time" required defaultValue={edit.item?.ends_at?.slice(0,5)}/></label></div><label>Dni tygodnia<input name="days" required defaultValue={edit.item?.day_mask?.join(",")||"1,2,3,4,5,6,7"}/><small>1 = poniedziałek, 7 = niedziela; wpisz np. 1,2,3,4,5.</small></label></>}{edit.kind==="ROLE"&&<label>Kolor<input name="color" type="color" defaultValue={edit.item?.color||"#7257d8"}/></label>}{edit.kind==="FUNCTION"&&<label>Opis<textarea name="description" defaultValue={edit.item?.description}/></label>}{edit.item&&<><input type="hidden" name="active" value="false"/><label className="check-label"><input name="active" value="true" type="checkbox" defaultChecked={edit.item.active}/> Aktywny element</label></>}<button disabled={busy} className="primary-button full"><Save/> Zapisz w wersji roboczej</button></form></aside></>}
function RoleDrawer({detail,employees,locations,close,save,remove}:{detail:{section:Section;assignments:any[];issues:any[]};employees:AdminEmployee[];locations:MatrixItem[];close:()=>void;save:(s:Section,id:string|null,p:Record<string,unknown>)=>void;remove:(s:Section,id:string)=>void}){
 const [location,setLocation]=useState("ALL");const [shift,setShift]=useState("ALL");const [onlyConflicts,setOnlyConflicts]=useState(false);const [selected,setSelected]=useState<any|null>(null);const [showIssues,setShowIssues]=useState(false);
 const issueDates=new Set(detail.issues.map(i=>i.date).filter(Boolean));const filtered=detail.assignments.filter(a=>(location==="ALL"||a.locationCode===location)&&(shift==="ALL"||a.shiftCode===shift)&&(!onlyConflicts||issueDates.has(a.date)));
 const grouped=new Map<string,any[]>();for(const a of filtered)grouped.set(a.date,[...(grouped.get(a.date)||[]),a]);const first=new Date("2026-07-01T12:00:00");const offset=(first.getDay()+6)%7;const cells=Array.from({length:offset+31},(_,i)=>i<offset?0:i-offset+1);
 return <><button className="drawer-scrim" onClick={close}/><aside className="drawer role-drawer"><div className="drawer-head"><div><p className="eyebrow">KALENDARZ I EDYCJA ROLI • WERSJA {detail.section.version}</p><h2>{detail.section.roleName} • lipiec 2026</h2></div><button className="icon-button" onClick={close}><X/></button></div><div className="drawer-content"><div className="role-summary"><span><b>{detail.assignments.length}</b><small>przydziałów</small></span><button className={detail.issues.length?"conflict-summary":""} onClick={()=>setShowIssues(true)}><b>{detail.issues.length}</b><small>konfliktów — pokaż</small></button><span><b>{statusPl[detail.section.status]}</b><small>status</small></span><button className="primary-button" onClick={()=>setSelected({})}><Plus/> Dodaj przydział</button></div>
 <div className="role-filters"><Filter/><button className={location==="ALL"?"active":""} onClick={()=>setLocation("ALL")}>Wszystkie lokale</button>{locations.filter(l=>l.active).map(l=><button className={location===l.code?"active":""} onClick={()=>setLocation(l.code)} key={l.id}>{l.name}</button>)}<select value={shift} onChange={e=>setShift(e.target.value)}><option value="ALL">Wszystkie zmiany</option><option value="RANO">Poranna</option><option value="SRODEK">Środkowa</option><option value="WIECZOR">Wieczorna</option><option value="EVENT">Eventowa</option></select><label><input type="checkbox" checked={onlyConflicts} onChange={e=>setOnlyConflicts(e.target.checked)}/> Tylko konflikty</label></div>
 <div className="calendar-color-legend"><span className="loc-krucza">Krucza</span><span className="loc-pawilony">Pawilony</span><i className="shift-morning"/>Poranna<i className="shift-mid"/>Środkowa<i className="shift-evening"/>Wieczorna<i className="shift-event"/>Eventowa</div>
 <div className="role-calendar-week">{days.map(d=><b key={d}>{d}</b>)}</div><div className="role-calendar">{cells.map((day,i)=>{const date=day?`2026-07-${String(day).padStart(2,"0")}`:"";const rows=grouped.get(date)||[];return <section data-date={date||undefined} className={!day?"blank":""} key={i}>{day&&<><strong>{day}</strong>{rows.map(a=><button onClick={()=>setSelected(a)} className={`role-assignment loc-${String(a.locationCode).toLowerCase()} shift-${String(a.shiftCode).toLowerCase()} ${issueDates.has(a.date)?"has-conflict":""}`} key={a.id}><b>{time(a.startsAt)}–{time(a.endsAt)}</b><span>{a.employeeName}</span><small>{a.location}{a.capability?` • ${capPl(a.capability)}`:""}</small>{a.manual&&<em>Edytowano</em>}</button>)}</>}</section>})}</div></div></aside>
 {showIssues&&<ConflictDrawer issues={detail.issues} close={()=>setShowIssues(false)} onDate={d=>{setOnlyConflicts(true);setShowIssues(false);document.querySelector(`[data-date="${d}"]`)?.scrollIntoView({behavior:"smooth"})}}/>}
 {selected&&<RoleAssignmentDrawer section={detail.section} assignment={selected.id?selected:null} employees={employees.filter(e=>e.active&&(e.primaryRole===detail.section.roleCode||e.capabilities.some(c=>c.role===detail.section.roleCode)))} locations={locations} close={()=>setSelected(null)} save={(id,p)=>{save(detail.section,id,p);setSelected(null)}} remove={id=>{remove(detail.section,id);setSelected(null)}}/>}</>}

function EmployeePortal({portal,openAvailability,openPreferences}:{portal:PortalWorkspace;openAvailability:()=>void;openPreferences:()=>void}){const e=portal.employee;const [selected,setSelected]=useState<PortalAssignment|null>(null);const grouped=new Map<string,PortalAssignment[]>();portal.assignments.forEach(a=>grouped.set(a.date,[...(grouped.get(a.date)||[]),a]));const first=new Date("2026-07-01T12:00:00"),offset=(first.getDay()+6)%7,cells=Array.from({length:offset+31},(_,i)=>i<offset?0:i-offset+1);
 function exportSchedule(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(portal.assignments.map(a=>({DATA:a.date,OD:time(a.startsAt),DO:time(a.endsAt),LOKAL:a.location,ZMIANA:shiftPl(a.shiftCode||""),FUNKCJA:capPl(a.capability||"")}))),"MÓJ_GRAFIK");XLSX.writeFile(wb,"MOJ_GRAFIK_LIPIEC_2026.xlsx")}
 function exportIcs(){const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//GRAFIK PRO//PL"];portal.assignments.forEach(a=>{const stamp=(x:string)=>new Date(x).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");lines.push("BEGIN:VEVENT",`UID:${a.id}@grafik-pro`,`DTSTART:${stamp(a.startsAt)}`,`DTEND:${stamp(a.endsAt)}`,`SUMMARY:Praca • ${a.location}`,`DESCRIPTION:${shiftPl(a.shiftCode||"")}`,"END:VEVENT")});lines.push("END:VCALENDAR");const blob=new Blob([lines.join("\r\n")],{type:"text/calendar"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="moj-grafik-lipiec-2026.ics";a.click();URL.revokeObjectURL(a.href)}
 return <><PageHead eyebrow="WIDOK PRACOWNIKA" title="Mój grafik i sprawy pracownicze" subtitle="Opublikowane zmiany, miesięczna dostępność i preferencje zalogowanego pracownika." actions={<><button className="secondary-button" onClick={exportSchedule}><Download/> Excel</button><button className="secondary-button" onClick={exportIcs}><CalendarDays/> Kalendarz ICS</button></>}/><div className="portal-grid portal-top"><section className="portal-profile"><UserRound/><h3>{e?.firstName} {e?.lastName}</h3><p>{e?.employeeNo} • {e?rolePl[e.primaryRole]||e.primaryRole:"—"}</p><span>{e?.locations?.map(x=>x.name).join(", ")}</span></section><section><h3>Moja dostępność</h3><button className="primary-button portal-action-visible" onClick={openAvailability}><CalendarDays/> Uzupełnij miesiąc</button><p>{portal.availability?.length||0} dni zapisanych. Historia zmian jest zachowana.</p></section><section><h3>Moje preferencje</h3><button className="primary-button portal-action-visible" onClick={openPreferences}><Plus/> Dodaj preferencję</button><p>{portal.preferences.length} zapisanych preferencji.</p></section></div>
 <section className="employee-calendar-card"><div className="matrix-demand-head"><div><h3>Moje opublikowane zmiany — lipiec 2026</h3><p>Kliknij zmianę, aby zobaczyć osoby pracujące z Tobą.</p></div></div><div className="calendar-color-legend"><span className="loc-krucza">Krucza</span><span className="loc-pawilony">Pawilony</span><i className="shift-morning"/>Poranna<i className="shift-mid"/>Środkowa<i className="shift-evening"/>Wieczorna</div><div className="role-calendar-week">{days.map(d=><b key={d}>{d}</b>)}</div><div className="employee-month-calendar">{cells.map((day,i)=>{const date=day?`2026-07-${String(day).padStart(2,"0")}`:"";return <section className={!day?"blank":""} key={i}>{day&&<><strong>{day}</strong>{(grouped.get(date)||[]).map(a=><button key={a.id} onClick={()=>setSelected(a)} className={`role-assignment loc-${String(a.locationCode).toLowerCase()} shift-${String(a.shiftCode).toLowerCase()}`}><b>{time(a.startsAt)}–{time(a.endsAt)}</b><small>{a.location} • {shiftPl(a.shiftCode||"")}</small></button>)}</>}</section>})}</div></section>{selected&&<CoworkerDrawer assignment={selected} close={()=>setSelected(null)}/>}</>}
function TimeView({employees,records,portal,location,setLocation,clock,busy}:{employees:AdminEmployee[];records:CompleteWorkspace["timeRecords"];portal:PortalWorkspace|null;location:string;setLocation:(x:string)=>void;clock:(a:"CHECK_IN"|"CHECK_OUT")=>void;busy:boolean}){const last=portal?.attendance?.[0];const active=last?.action==="CHECK_IN";const exportRows=()=>downloadCsv("ewidencja-czasu-2026-07.csv",records.map(r=>{const e=employees.find(x=>x.id===r.employee_id);return {pracownik:e?`${e.firstName} ${e.lastName}`:"",data:r.work_date,plan_od:r.planned_start,plan_do:r.planned_end,faktycznie_od:r.actual_start,faktycznie_do:r.actual_end,status:r.status}}));return <><PageHead eyebrow="EWIDENCJA CZASU" title="Rozpoczęcie i zakończenie pracy" subtitle="Zapis jest przypisany do zalogowanego pracownika, wybranego lokalu i bieżącej geolokalizacji." actions={<button className="secondary-button" onClick={exportRows}><Download/> Eksport CSV</button>}/>{portal?.employee&&<section className="clock-panel"><div><Clock3/><span><small>AKTUALNY STATUS</small><b>{active?`Praca rozpoczęta • ${last.location}`:"Poza pracą"}</b>{last&&<em>Ostatnia operacja: {new Date(last.occurredAt).toLocaleString("pl-PL")}</em>}</span></div><label>Lokal<select value={location} onChange={e=>setLocation(e.target.value)}>{portal.employee.locations.map(l=><option key={l.code} value={l.code}>{l.name}</option>)}</select></label><button disabled={busy} className={active?"danger-button":"primary-button"} onClick={()=>clock(active?"CHECK_OUT":"CHECK_IN")}>{active?"Zakończ pracę":"Rozpocznij pracę"}</button></section>}<div className="admin-table"><div className="admin-tr attendance head"><span>Data i godzina</span><span>Pracownik</span><span>Lokal</span><span>Operacja</span></div>{portal?.attendance?.map(a=><div className="admin-tr attendance" key={a.id}><span>{new Date(a.occurredAt).toLocaleString("pl-PL")}</span><span>{portal.employee?.firstName} {portal.employee?.lastName}</span><span>{a.location}</span><span>{a.action==="CHECK_IN"?"Rozpoczęcie pracy":"Zakończenie pracy"}</span></div>)}</div></>}
function IntegrationView({runs,onExport,onImport,busy}:{runs:CompleteWorkspace["integrationRuns"];onExport:()=>void;onImport:(f:File)=>void;busy:boolean}){return <><PageHead eyebrow="INTEGRACJE" title="Kadromierz — import i eksport" subtitle="GRAFIK PRO zachowuje własny model danych. Integracja służy wymianie plików i może zostać wyłączona bez utraty historii." actions={<button disabled={busy} className="primary-button" onClick={onExport}><Download/> Eksport grafiku</button>}/><div className="integration-cards"><section><FileUp/><h3>Import z Kadromierza</h3><p>Urlopy, nieobecności i dostępność. Plik wymaga numeru pracownika i daty.</p><label className="secondary-button">Wybierz plik CSV<input hidden type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&onImport(e.target.files[0])}/></label></section><section><Download/><h3>Eksport do Kadromierza</h3><p>Eksport obejmuje wyłącznie opublikowany grafik po zatwierdzeniu właściciela.</p><button onClick={onExport}>Przygotuj eksport</button></section></div><div className="admin-table"><div className="admin-tr integration head"><span>Data</span><span>Kierunek</span><span>Zakres</span><span>Plik</span><span>Status</span><span></span></div>{runs.map(r=><div className="admin-tr integration" key={r.id}><span>{new Date(r.created_at).toLocaleString("pl-PL")}</span><span>{r.direction==="IMPORT"?"Import":"Eksport"}</span><span>{r.integration}</span><span>{r.file_name||"—"}</span><span>{r.status}</span><span><ChevronRight/></span></div>)}</div></>}
function AvailabilityDrawer({employee,existing,close,save,busy}:{employee:AdminEmployee;existing:PortalWorkspace["availability"];close:()=>void;save:(entries:{date:string;status:string}[],fill:boolean)=>void;busy:boolean}){const initial=Object.fromEntries(existing.map(x=>[x.date,x.status]));const [marks,setMarks]=useState<Record<string,string>>(initial);const [mode,setMode]=useState("UNAVAILABLE");const first=new Date("2026-07-01T12:00:00"),offset=(first.getDay()+6)%7,cells=Array.from({length:offset+31},(_,i)=>i<offset?0:i-offset+1);const toggle=(d:number)=>{const date=`2026-07-${String(d).padStart(2,"0")}`;setMarks(m=>({...m,[date]:m[date]===mode?"":mode}))};const submit=()=>{const entries=Object.entries(marks).filter(([,s])=>s).map(([date,status])=>({date,status}));const onlyUnavailable=entries.length>0&&entries.every(x=>x.status==="UNAVAILABLE");let fill=false;if(onlyUnavailable){fill=confirm("Zaznaczono tylko niedostępność. Czy oznaczyć wszystkie pozostałe dni lipca jako dostępne? Ta decyzja zostanie zapisana w historii.")}save(entries,fill)};return <><button className="drawer-scrim" onClick={close}/><aside className="drawer role-drawer"><div className="drawer-head"><div><p className="eyebrow">PORTAL PRACOWNIKA</p><h2>Dostępność • lipiec 2026</h2><small>{employee.firstName} {employee.lastName}</small></div><button className="icon-button" onClick={close}><X/></button></div><div className="drawer-content"><div className="availability-toolbar"><button className={mode==="AVAILABLE"?"available active":"available"} onClick={()=>setMode("AVAILABLE")}>Dostępny</button><button className={mode==="UNAVAILABLE"?"unavailable active":"unavailable"} onClick={()=>setMode("UNAVAILABLE")}>Niedostępny</button><button onClick={()=>setMarks({})}>Wyczyść</button></div><p>Klikaj kolejne dni wybranym kolorem. Jeśli podasz wyłącznie niedostępność, aplikacja zapyta, czy pozostałe dni uznać za dostępne.</p><div className="role-calendar-week">{days.map(d=><b key={d}>{d}</b>)}</div><div className="availability-calendar">{cells.map((d,i)=><button type="button" disabled={!d} key={i} className={d?(marks[`2026-07-${String(d).padStart(2,"0")}`]||"unset").toLowerCase():"blank"} onClick={()=>d&&toggle(d)}>{d||""}</button>)}</div><button disabled={busy} className="primary-button full" onClick={submit}><Save/> Zapisz dostępność miesiąca</button></div></aside></>}
function ConflictDrawer({issues,close,onDate}:{issues:any[];close:()=>void;onDate:(d:string)=>void}){return <><button className="drawer-scrim top" onClick={close}/><aside className="drawer complete-drawer top"><div className="drawer-head"><div><p className="eyebrow">KONFLIKTY I BRAKI</p><h2>{issues.length} pozycji wymagających uwagi</h2></div><button className="icon-button" onClick={close}><X/></button></div><div className="drawer-content conflict-list">{issues.map(x=><button key={x.id} onClick={()=>x.date&&onDate(x.date)}><AlertTriangle/><span><b>{x.type==="SHORTAGE"?"Brak obsady":x.type==="UNAVAILABLE"?"Pracownik niedostępny":x.type==="OVERLAP"?"Nakładające się zmiany":x.type}</b><small>{x.date} • {x.message}</small>{x.required!=null&&<em>Wymaganych: {x.required} • przypisanych: {x.assigned} • brakuje: {Math.max(0,x.required-x.assigned)}</em>}{x.unavailable?.length>0&&<em>Niedostępni tego dnia: {x.unavailable.map((u:any)=>`${u.name} (${u.source})`).join(", ")}</em>}</span><ChevronRight/></button>)}</div></aside></>}
function RoleAssignmentDrawer({section,assignment,employees,locations,close,save,remove}:{section:Section;assignment:any|null;employees:AdminEmployee[];locations:MatrixItem[];close:()=>void;save:(id:string|null,p:Record<string,unknown>)=>void;remove:(id:string)=>void}){return <><button className="drawer-scrim top" onClick={close}/><aside className="drawer complete-drawer top"><div className="drawer-head"><div><p className="eyebrow">WERSJA ROBOCZA • {section.roleName}</p><h2>{assignment?"Edytuj przydział":"Dodaj przydział"}</h2></div><button className="icon-button" onClick={close}><X/></button></div><form className="drawer-content" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save(assignment?.id||null,Object.fromEntries(f.entries()))}}><label>Pracownik<select name="employeeId" required defaultValue={assignment?.employeeId}>{employees.map(e=><option value={e.id} key={e.id}>{e.firstName} {e.lastName} • {e.employeeNo}</option>)}</select></label><label>Data<input type="date" name="date" required defaultValue={assignment?.date||"2026-07-01"}/></label><label>Lokal<select name="locationCode" required defaultValue={assignment?.locationCode}>{locations.filter(x=>x.active).map(l=><option value={l.code} key={l.id}>{l.name}</option>)}</select></label><label>Typ zmiany<select name="shiftCode" defaultValue={assignment?.shiftCode||"RANO"}><option value="RANO">Poranna</option><option value="SRODEK">Środkowa</option><option value="WIECZOR">Wieczorna</option><option value="EVENT">Eventowa</option></select></label><div className="form-row"><label>Od<input name="startsAt" type="time" required defaultValue={assignment?timeInput(assignment.startsAt):"10:00"}/></label><label>Do<input name="endsAt" type="time" required defaultValue={assignment?timeInput(assignment.endsAt):"17:00"}/></label></div><label>Funkcja<input name="capability" defaultValue={assignment?.capability||""} placeholder="np. HOST"/></label><button className="primary-button full"><Save/> Zapisz przydział</button>{assignment&&<button type="button" className="danger-button full" onClick={()=>remove(assignment.id)}><Trash2/> Usuń przydział</button>}</form></aside></>}
function CoworkerDrawer({assignment,close}:{assignment:PortalAssignment;close:()=>void}){return <><button className="drawer-scrim" onClick={close}/><aside className="drawer complete-drawer"><div className="drawer-head"><div><p className="eyebrow">SZCZEGÓŁY ZMIANY</p><h2>{assignment.date} • {time(assignment.startsAt)}–{time(assignment.endsAt)}</h2><small>{assignment.location} • {shiftPl(assignment.shiftCode||"")}</small></div><button className="icon-button" onClick={close}><X/></button></div><div className="drawer-content coworker-list"><h3>Osoby na tej zmianie</h3>{assignment.coworkers?.length?assignment.coworkers.map((x,i)=><div key={i}><UserRound/><span><b>{x.name}</b><small>{rolePl[x.role]||x.role}{x.capability?` • ${capPl(x.capability)}`:""}</small></span></div>):<p>Nie ma innych przypisanych osób.</p>}</div></aside></>}
function PreferenceDrawer({employee,locations,close,save,busy}:{employee:AdminEmployee;locations:{code:string;name:string}[];close:()=>void;save:(f:HTMLFormElement)=>void;busy:boolean}){const [type,setType]=useState("PREFERRED_LOCATION");return <><button className="drawer-scrim" onClick={close}/><aside className="drawer complete-drawer"><div className="drawer-head"><div><p className="eyebrow">PORTAL PRACOWNIKA</p><h2>Nowa preferencja</h2></div><button className="icon-button" onClick={close}><X/></button></div><form className="drawer-content" onSubmit={e=>{e.preventDefault();save(e.currentTarget)}}><p>{employee.firstName} {employee.lastName}</p><label>Rodzaj<select name="type" value={type} onChange={e=>setType(e.target.value)}><option value="PREFERRED_LOCATION">Preferowany lokal</option><option value="PREFERRED_SHIFT">Preferowana zmiana</option><option value="NON_PREFERRED_SHIFT">Niepreferowana zmiana</option><option value="PREFERRED_DAYS">Preferowane dni tygodnia</option><option value="OTHER">Inna preferencja</option></select></label>{type==="PREFERRED_LOCATION"&&<label>Lokal<select name="value"><option value="NONE">Bez preferencji</option>{locations.map(l=><option value={l.code} key={l.code}>{l.name}</option>)}</select></label>}{(type==="PREFERRED_SHIFT"||type==="NON_PREFERRED_SHIFT")&&<label>Zmiana<select name="value"><option value="RANO">Poranna</option><option value="SRODEK">Środkowa</option><option value="WIECZOR">Wieczorna</option></select></label>}{type==="PREFERRED_DAYS"&&<label>Dni tygodnia<input name="value" placeholder="np. poniedziałek, środa" required/></label>}<div className="form-row"><label>Od<input name="from" type="date" required defaultValue="2026-07-01"/></label><label>Do<input name="to" type="date" required defaultValue="2026-07-31"/></label></div><label>Uwagi<textarea name="note"/></label><button disabled={busy} className="primary-button full"><Save/> Zapisz preferencję</button></form></aside></>}
function translateError(x:string){return ({FORBIDDEN:"Nie masz uprawnień do tej operacji.",NO_DRAFT:"Najpierw utwórz wersję roboczą Matrixa.",ITEM_NOT_IN_DRAFT:"Ten element pochodzi z aktywnej wersji. Otwórz wersję roboczą i wybierz jego kopię."} as Record<string,string>)[x]||x}
function capPl(x:string){return ({HOST:"Host",CLOSE_SHIFT:"Zamknięcie zmiany",ROLE_MANAGER:"Menadżer roli",LOCATION_MANAGER:"Menadżer lokalu",STANDBY:"Rezerwa",ROTATIONAL:"Rotacyjny",OPEN_SHIFT:"Otwarcie zmiany"} as Record<string,string>)[x]||x}
function contractPl(x?:string){return ({UMOWA_O_PRACE:"Umowa o pracę",ZLECENIE:"Zlecenie",CZESC_ETATU:"Część etatu",B2B:"B2B",INNE:"Inna"} as Record<string,string>)[x||""]||"—"}
function shiftPl(x:string){return ({RANO:"Zmiana poranna",SRODEK:"Zmiana środkowa",WIECZOR:"Zmiana wieczorna"} as Record<string,string>)[x]||x}
function preferencePl(x:string){return ({AVAILABLE:"Dostępność",UNAVAILABLE:"Niedostępność",PREFERRED_SHIFT:"Preferowana zmiana",PREFERRED_LOCATION:"Preferowany lokal",LEAVE:"Urlop",SICKNESS:"Zwolnienie",OTHER:"Inne"} as Record<string,string>)[x]||x}
function scenarioPl(x:string){return ({BASE:"Bazowy",LOW:"Niski ruch",HIGH:"Wysoki ruch",WEEKEND:"Weekend",EVENT:"Event",SUMMER:"Sezon letni",EMERGENCY:"Awaryjny"} as Record<string,string>)[x]||x}
function time(x?:string){return x?new Date(x).toLocaleTimeString("pl-PL",{hour:"2-digit",minute:"2-digit"}):"—"}
function timeInput(x?:string){if(!x)return "";const d=new Date(x);return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}
function downloadCsv(name:string,rows:Record<string,unknown>[]){if(!rows.length)return;const headers=Object.keys(rows[0]);const cell=(x:unknown)=>`"${String(x??"").replaceAll('"','""')}"`;const blob=new Blob(["\ufeff"+[headers.join(";"),...rows.map(r=>headers.map(h=>cell(r[h])).join(";"))].join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
