import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const headers={...cors,"Content-Type":"application/json","Cache-Control":"no-store"};
type J=Record<string,any>; type Gene=string|null;
type Slot={id:string,date:string,shiftCode:string,startsAt:string,endsAt:string,localStart:string,localEnd:string,locationId:string,locationCode:string,role:string,fn?:string};
type Candidate={genes:Gene[],hard:number,unfilled:number,soft:number,score:number,metrics:J};
const err=(e:any)=>e?.message||e?.details||e?.hint||e?.code||(typeof e==="string"?e:JSON.stringify(e));
function rng(seed:number){let x=seed|0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
const mins=(a:string,b:string)=>Math.max(0,(Date.parse(b)-Date.parse(a))/60000);
const clockMins=(t:string)=>{const [h,m]=String(t).split(":").map(Number);return h*60+m};
function localSpan(s:Slot){const start=clockMins(s.localStart),rawEnd=clockMins(s.localEnd);return[start,rawEnd<=start?rawEnd+1440:rawEnd] as const}
function weekKey(d:string){const x=new Date(d+"T12:00:00Z"),n=(x.getUTCDay()+6)%7;x.setUTCDate(x.getUTCDate()-n);return x.toISOString().slice(0,10)}
const weekend=(d:string)=>{const n=new Date(d+"T12:00:00Z").getUTCDay();return n===0||n===6};
function zoned(date:string,time:string,zone:string){const base=Date.parse(`${date}T${time}Z`),f=new Intl.DateTimeFormat("en-CA",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}),p=Object.fromEntries(f.formatToParts(new Date(base)).filter(x=>x.type!=="literal").map(x=>[x.type,x.value])),shown=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);return new Date(base-(shown-base)).toISOString()}
function slotsFor(input:J){const month=input.month.slice(0,7),end=new Date(`${month}-01T12:00:00Z`);end.setUTCMonth(end.getUTCMonth()+1);const tm=new Map(input.templates.map((x:J)=>[x.id,x])),out:Slot[]=[];
  for(let d=new Date(`${month}-01T12:00:00Z`);d<end;d.setUTCDate(d.getUTCDate()+1)){const date=d.toISOString().slice(0,10),dow=d.getUTCDay()||7;for(const q of input.demand){const t:any=tm.get(q.templateId);if(!t||!t.days.includes(dow)||!(q.scenario==="BASE"||q.scenario===input.scenario))continue;const ed=new Date(d);if(t.end<=t.start)ed.setUTCDate(ed.getUTCDate()+1);for(let n=0;n<q.count;n++)out.push({id:`${date}|${t.id}|${q.role}|${q.function||""}|${n}`,date,shiftCode:t.code,startsAt:zoned(date,t.start,t.timezone),endsAt:zoned(ed.toISOString().slice(0,10),t.end,t.timezone),localStart:t.start,localEnd:t.end,locationId:t.locationId,locationCode:t.locationCode,role:q.role,fn:q.function||undefined})}}
  return out.sort((a,b)=>a.startsAt.localeCompare(b.startsAt)||a.id.localeCompare(b.id));}

function engine(input:J){input.scenario=input.scenario||"BASE";const slots=slotsFor(input),employees=input.employees as J[],byId=new Map(employees.map(e=>[e.id,e])),weights=input.profile.weights||{},availability=new Map<string,J>(),prefs=new Map<string,J[]>(),blocks=new Map<string,J[]>();
  const weight=(key:string,fallback:number)=>{const n=Number(weights[key]);return Number.isFinite(n)?n:fallback};
  for(const a of input.availability||[])availability.set(`${a.employeeId}|${a.date}`,a);for(const p of input.preferences||[]){const a=prefs.get(p.employeeId)||[];a.push(p);prefs.set(p.employeeId,a)}for(const b of input.hardBlocks||[]){const a=blocks.get(b.employeeId)||[];a.push(b);blocks.set(b.employeeId,a)}
  const blocked=(e:J,s:Slot)=>{const a=availability.get(`${e.id}|${s.date}`);if(a){if(!a.available)return true;const [start,end]=localSpan(s),earliest=a.earliestStart?clockMins(a.earliestStart):null;let latest=a.latestEnd?clockMins(a.latestEnd):null;if(latest!==null&&earliest!==null&&latest<=earliest)latest+=1440;if((earliest!==null&&start<earliest)||(latest!==null&&end>latest))return true}return(blocks.get(e.id)||[]).some(b=>b.from<=s.date&&b.to>=s.date)};
  const staticOK=(e:J,s:Slot)=>e.locations.some((l:J)=>l.id===s.locationId)&&(e.roles.includes(s.role)||e.role===s.role)&&(!s.fn||e.capabilities.some((c:J)=>c.code===s.fn&&(!c.role||c.role===s.role)&&(!c.location||c.location===s.locationCode)))&&!(e.employmentStart&&s.date<e.employmentStart)&&!(e.employmentEnd&&s.date>e.employmentEnd)&&!(e.noWeekends&&weekend(s.date))&&!(e.onlyMorning&&s.localStart>="15:00")&&!(e.onlyEvening&&s.localStart<"14:00")&&!blocked(e,s);
  function preferenceViolations(e:J,s:Slot){let n=0;for(const q of prefs.get(e.id)||[]){if(q.from>s.date||q.to<s.date)continue;if(q.type==="PREFERRED_SHIFT"&&q.value?.code!==s.shiftCode)n++;if(q.type==="PREFERRED_LOCATION"&&q.value?.code!==s.locationCode)n++;if(q.type==="OTHER"&&q.value?.dayOff)n++}const a=availability.get(`${e.id}|${s.date}`);if(a?.preferredShiftCode&&a.preferredShiftCode!==s.shiftCode)n++;if(e.preferredShift&&e.preferredShift!==s.shiftCode)n++;return n}
  const eligible=slots.map(s=>employees.filter(e=>staticOK(e,s)));const scarcity=[...slots.keys()].sort((a,b)=>eligible[a].length-eligible[b].length||Number(!!slots[b].fn)-Number(!!slots[a].fn)||slots[a].startsAt.localeCompare(slots[b].startsAt));
  function state(){return{byEmp:new Map<string,number[]>(),month:new Map<string,number>(),week:new Map<string,number>(),days:new Map<string,Map<string,number>>()}}
  function add(st:J,id:string,i:number){const s=slots[i],m=mins(s.startsAt,s.endsAt),a=st.byEmp.get(id)||[];a.push(i);st.byEmp.set(id,a);st.month.set(id,(st.month.get(id)||0)+m);const wk=`${id}|${weekKey(s.date)}`;st.week.set(wk,(st.week.get(wk)||0)+m);const dm=st.days.get(id)||new Map();dm.set(s.date,(dm.get(s.date)||0)+1);st.days.set(id,dm)}
  function remove(st:J,id:string,i:number){const s=slots[i],m=mins(s.startsAt,s.endsAt),a=(st.byEmp.get(id)||[]).filter((x:number)=>x!==i);st.byEmp.set(id,a);st.month.set(id,(st.month.get(id)||0)-m);const wk=`${id}|${weekKey(s.date)}`;st.week.set(wk,(st.week.get(wk)||0)-m);const dm=st.days.get(id)||new Map(),n=(dm.get(s.date)||1)-1;n?dm.set(s.date,n):dm.delete(s.date);st.days.set(id,dm)}
  function streak(dm:Map<string,number>,extra?:string){const ds=[...new Set([...dm.keys(),...(extra?[extra]:[])])].sort();let n=0,max=0,last=0;for(const d of ds){const t=Date.parse(d+"T12:00:00Z");n=t-last===86400000?n+1:1;last=t;max=Math.max(max,n)}return max}
  function feasible(e:J,i:number,st:J){const s=slots[i],m=mins(s.startsAt,s.endsAt),rest=Number(e.minimumRest??660)*60000;if((st.month.get(e.id)||0)+m>e.maxMonthly||(st.week.get(`${e.id}|${weekKey(s.date)}`)||0)+m>e.maxWeekly)return false;if(((st.days.get(e.id)||new Map()).get(s.date)||0)>=Number(input.matrix?.settings?.maxShiftsPerDay??7))return false;if(streak(st.days.get(e.id)||new Map(),s.date)>e.maxConsecutiveDays)return false;for(const j of st.byEmp.get(e.id)||[]){const x=slots[j];if(Date.parse(s.startsAt)<Date.parse(x.endsAt)+rest&&Date.parse(s.endsAt)>Date.parse(x.startsAt)-rest)return false}return true}
  function penalty(e:J,i:number,st:J){const s=slots[i],m=mins(s.startsAt,s.endsAt);let p=e.rate*m/60*weight("cost",1);p+=preferenceViolations(e,s)*weight("preference",80);if(!e.locations.some((l:J)=>l.id===s.locationId&&l.home))p+=weight("homeLocation",15);const after=(st.month.get(e.id)||0)+m;if(after>e.nominal)p+=(after-Math.max(e.nominal,st.month.get(e.id)||0))/60*weight("overtime",250);p+=((st.month.get(e.id)||0)/Math.max(1,e.nominal))*weight("fairness",40);return p}
  function validate(genes:Gene[]){let hard=0;const st=state();for(let i=0;i<genes.length;i++){const id=genes[i];if(!id)continue;const e=byId.get(id);if(!e||!eligible[i].some(x=>x.id===id)||!feasible(e,i,st)){hard++;continue}add(st,id,i)}if(input.budget?.hardLimit&&input.budget.amount>0){let cost=0;for(let i=0;i<genes.length;i++)if(genes[i])cost+=(byId.get(genes[i]!)?.rate||0)*mins(slots[i].startsAt,slots[i].endsAt)/60;if(cost>input.budget.amount)hard++}return hard}
  function evaluate(genes:Gene[]):Candidate{const st=state();for(let i=0;i<genes.length;i++){const id=genes[i];if(id)add(st,id,i)}let cost=0,pref=0,home=0,nom=0,overtime=0;const weekends:number[]=[],ratios:number[]=[];for(const e of employees){const m=st.month.get(e.id)||0;cost+=m/60*e.rate;nom+=Math.abs(m-e.nominal);overtime+=Math.max(0,m-e.nominal)/60;ratios.push(m/Math.max(1,e.nominal));weekends.push((st.byEmp.get(e.id)||[]).filter((i:number)=>weekend(slots[i].date)).length)}for(let i=0;i<genes.length;i++){const id=genes[i];if(!id)continue;const e=byId.get(id)!;pref+=preferenceViolations(e,slots[i]);if(!e.locations.some((l:J)=>l.id===slots[i].locationId&&l.home))home++}const avg=weekends.reduce((a,b)=>a+b,0)/Math.max(1,weekends.length),variance=weekends.reduce((a,b)=>a+(b-avg)**2,0),loadAvg=ratios.reduce((a,b)=>a+b,0)/Math.max(1,ratios.length),workloadVariance=ratios.reduce((a,b)=>a+(b-loadAvg)**2,0),unfilled=genes.filter(x=>!x).length,hard=validate(genes),soft=cost*weight("cost",1)+pref*weight("preference",80)+home*weight("homeLocation",15)+nom/60*weight("nominal",30)+overtime*weight("overtime",250)+variance*weight("weekendFairness",25)+workloadVariance*weight("fairness",40);return{genes,hard,unfilled,soft,score:hard*1e15+unfilled*1e10+soft,metrics:{totalSlots:slots.length,filled:slots.length-unfilled,unfilled,cost,preferenceViolations:pref,homeLocationViolations:home,nominalDeviationHours:nom/60,overtimeHours:overtime,weekendVariance:variance,workloadVariance}}}
  function repair(source:Gene[],rand:()=>number){const genes:Array<Gene>=Array(slots.length).fill(null),st=state();for(const i of scarcity){const id=source[i],e=id?byId.get(id):undefined;if(id&&e&&eligible[i].some(x=>x.id===id)&&feasible(e,i,st)){genes[i]=id;add(st,id,i)}}for(const i of scarcity){if(genes[i])continue;let best:J|undefined,bp=Infinity;for(const e of eligible[i])if(feasible(e,i,st)){const p=penalty(e,i,st)+rand();if(p<bp){best=e;bp=p}}if(best){genes[i]=best.id;add(st,best.id,i)}}
    // Bounded augmenting repair. The bounds are part of the request CPU budget:
    // later generations revisit other shortages with different deterministic seeds.
    let repaired=0;
    for(const i of scarcity){if(genes[i]||repaired>=12)continue;let solved=false;
      for(const e of eligible[i].slice(0,6)){if(solved)break;for(const j of [...(st.byEmp.get(e.id)||[])].slice(0,8)){remove(st,e.id,j);if(feasible(e,i,st)){for(const alt of eligible[j].slice(0,6))if(alt.id!==e.id&&feasible(alt,j,st)){genes[j]=alt.id;add(st,alt.id,j);genes[i]=e.id;add(st,e.id,i);repaired++;solved=true;break}}if(!solved)add(st,e.id,j);if(solved)break}}
    }return evaluate(genes)}
  function baseline(){const g:Array<Gene>=Array(slots.length).fill(null),used=new Set<number>();for(const a of input.baselineAssignments||[]){const i=slots.findIndex((s,k)=>!used.has(k)&&s.date===a.date&&s.shiftCode===a.shiftCode&&s.locationId===a.locationId&&s.role===a.role&&(s.fn||null)===(a.function||null));if(i>=0){g[i]=a.employeeId;used.add(i)}}return g}
  const cmp=(a:Candidate,b:Candidate)=>a.hard-b.hard||a.unfilled-b.unfilled||a.soft-b.soft;
  function initialOne(seed:number,index:number,pop:Candidate[]){const r=rng(seed+index*65537);if(index===0)return repair(baseline(),r);if(index===1)return repair(Array(slots.length).fill(null),r);const parent=pop[index%Math.max(1,pop.length)]?.genes||Array(slots.length).fill(null),g=[...parent];for(let i=0;i<g.length;i++)if(r()<.08)g[i]=null;return repair(g,r)}
  function unique(a:Candidate[]){const seen=new Set<string>();return a.sort(cmp).filter(c=>{const k=c.genes.join("|");if(seen.has(k))return false;seen.add(k);return true}).slice(0,16)}
  function evolveOne(pop:Candidate[],seed:number,generation:number){const r=rng(seed+generation*104729),pool=pop.slice(0,Math.max(2,Math.ceil(pop.length/2))),a=pool[Math.floor(r()*pool.length)],b=pool[Math.floor(r()*pool.length)],g=a.genes.map((x,i)=>r()<.5?x:b.genes[i]);for(let i=0;i<g.length;i++)if(r()<Number(input.profile.mutationRate??.08))g[i]=r()<.7?null:(eligible[i][Math.floor(r()*Math.max(1,eligible[i].length))]?.id||null);return unique([...pop,repair(g,r)])}
  function exportCandidates(pop:Candidate[]){return unique(pop).slice(0,Number(input.profile.alternativesCount??3)).map((c,rank)=>({rank:rank+1,score:c.score,hardViolations:c.hard,metrics:{...c.metrics,softPenalty:c.soft,ranking:[c.hard,c.unfilled,c.soft],engineVersion:"ALPHA_15_V4"},unfilled:slots.filter((_,i)=>!c.genes[i]),assignments:c.genes.flatMap((id,i)=>id?[{slotId:slots[i].id,employeeId:id,date:slots[i].date,shiftCode:slots[i].shiftCode,startsAt:slots[i].startsAt,endsAt:slots[i].endsAt,localStart:slots[i].localStart,localEnd:slots[i].localEnd,locationId:slots[i].locationId,role:slots[i].role,function:slots[i].fn||null}]:[])}))}
  return{initialOne,evolveOne,exportCandidates,cmp};
}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});let activeRunId:string|undefined,client:any;try{if(req.method!=="POST")return new Response(JSON.stringify({error:"METHOD_NOT_ALLOWED"}),{status:405,headers});const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))return new Response(JSON.stringify({error:"UNAUTHORIZED"}),{status:401,headers});client=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const body=await req.json(),action=String(body.action||"START").toUpperCase();
  activeRunId=body.runId as string|undefined;
  if(action==="START"){const {data:input,error}=await client.rpc("optimizer_prepare_v2",{p_month:body.month,p_profile_code:body.profile||"BALANCED",p_scenario_code:body.scenario||"BASE",p_seed:body.seed||null});if(error)throw error;activeRunId=input.runId;const initTarget=Math.max(12,Math.min(16,Number(input.profile.populationSize||12))),{error:ce}=await client.rpc("optimizer_save_state_v3",{p_run_id:input.runId,p_expected_generation:0,p_checkpoint:{population:[],initCursor:0,initTarget,baselineRanking:null},p_metrics:{phase:"INITIALIZING",progress:0}});if(ce)throw ce;return new Response(JSON.stringify({runId:input.runId,generation:0,targetGenerations:Math.max(24,Math.min(100,input.profile.generations||32)),initializing:true,initCursor:0,initTarget}),{headers})}
  const {data:state,error:se}=await client.rpc("optimizer_run_state_v2",{p_run_id:body.runId});if(se)throw se;if(!state)throw new Error("RUN_NOT_FOUND");const e=engine(state.input),pop=(state.checkpoint?.population||[]) as Candidate[];
  if(action==="INIT"){const cursor=Number(state.checkpoint?.initCursor||0),target=Number(state.checkpoint?.initTarget||12);if(cursor>=target)return new Response(JSON.stringify({runId:body.runId,initializing:false,initCursor:cursor,initTarget:target,baselineRanking:state.checkpoint?.baselineRanking}),{headers});const next=e.initialOne(state.input.seed,cursor,pop),nextPop=[...pop,next].sort(e.cmp).slice(0,16),nextCursor=cursor+1,baselineRanking=state.checkpoint?.baselineRanking||(cursor===0?[next.hard,next.unfilled,next.soft]:null),{error}=await client.rpc("optimizer_save_init_v4",{p_run_id:body.runId,p_expected_cursor:cursor,p_checkpoint:{population:nextPop,initCursor:nextCursor,initTarget:target,baselineRanking},p_metrics:{phase:"INITIALIZING",progress:Math.round(10*nextCursor/target),best:nextPop[0].metrics,baselineRanking}});if(error)throw error;return new Response(JSON.stringify({runId:body.runId,initializing:nextCursor<target,initCursor:nextCursor,initTarget:target,best:nextPop[0].metrics,baselineRanking}),{headers})}
  if(action==="STEP"){if(!pop.length||Number(state.checkpoint?.initCursor||0)<Number(state.checkpoint?.initTarget||8))throw new Error("INITIAL_POPULATION_INCOMPLETE");const next=e.evolveOne(pop,state.input.seed,state.generation),{error}=await client.rpc("optimizer_checkpoint_v2",{p_run_id:body.runId,p_expected_generation:state.generation,p_checkpoint:{...state.checkpoint,population:next},p_metrics:{best:next[0].metrics}});if(error)throw error;return new Response(JSON.stringify({runId:body.runId,generation:state.generation+1,targetGenerations:state.targetGenerations,best:next[0].metrics,done:state.generation+1>=state.targetGenerations}),{headers})}
  if(action==="FINALIZE"){
    const phase=String(state.summary?.phase||"");
    if(phase!=="FINALIZING"){
      const candidates=e.exportCandidates(pop);if(candidates.length!==3||candidates.some((c:J)=>c.hardViolations))throw new Error("THREE_HARD_VALID_CANDIDATES_REQUIRED");
      const {data,error}=await client.rpc("optimizer_begin_finalize_v4",{p_run_id:body.runId,p_name:body.name,p_candidates:candidates});if(error)throw error;
      return new Response(JSON.stringify(data),{headers});
    }
    const cursor=Number(state.checkpoint?.finalizeCursor||0),target=Number(state.checkpoint?.finalizeTarget||3);
    if(cursor<target){const {data,error}=await client.rpc("optimizer_materialize_next_v4",{p_run_id:body.runId});if(error)throw error;return new Response(JSON.stringify(data),{headers})}
    const {data,error}=await client.rpc("optimizer_complete_finalize_v4",{p_run_id:body.runId});if(error)throw error;return new Response(JSON.stringify(data),{headers});
  }
  if(action==="STATUS")return new Response(JSON.stringify({runId:body.runId,generation:state.generation,targetGenerations:state.targetGenerations,status:state.status,summary:state.summary}),{headers});throw new Error("UNKNOWN_ACTION");
}catch(e){try{if(activeRunId&&client){const {error}=await client.rpc("optimizer_abort_finalize_v4",{p_run_id:activeRunId,p_error:err(e)});if(error)await client.rpc("optimizer_fail_v3",{p_run_id:activeRunId,p_error:err(e)})}}catch{}return new Response(JSON.stringify({error:err(e)}),{status:400,headers})}});
